### ISSUE TITLE
Initialize with node features

### ISSUE THREAD

**Issue by kmichael08** [BaseModelAI/cleora#26]
Is it possible to leverage the information of the node features, e.g. initialize the embeddings?

**Comment by barbara3430** [comment]
Hi Michał, nice to hear from you :)
It makes sense to initialize Cleora with precomputed node features instead of random initialization. This way, the obtained node embeddings will keep the information prior induced by the initial embeddings. During training, graph-based knowledge will be additionally incorporated within the embeddings. You can attempt to load precomputed vectors as input, or wait for our implementation of easy custom embedding loading which is due in April :)

**Comment by kmichael08** [comment]
Great, thanks! Looking forward to seeing this feature :)
