### ISSUE TITLE
edges with weight

### ISSUE THREAD

**Issue by saustar** [BaseModelAI/cleora#43]
hi 
I am not able to find two things:
1. How to give data where edges are present with some weight?? So that edge weights are taken into embedding calculation.
2. Cold start problems? How to use embeddings for cold start?

**Comment by barbara3430** [comment]
Dear @saustar 
1. I am assuming that by cold start you mean the situation where no graph interactions exist for a given node (e.g. a product freshly added to inventory). For such cases a mean embedding of a selected group of nodes can be substituted (e.g. if your product has a certain characteristic which is important for your setting - it is let's say a car, you can use a mean embedding of other cars). You can also modify Cleora's code a bit to initialize a new node with an embedding coming from another representation model, e.g. a picture or text embedding of node properties, instead of random initialization. This way, Cleora will take into account the similarity relations expressed by upstream embeddings and the introduction of cold-start items will become much easier. We are currently working on supporting this conveniently as a separate mode of operation.

Some experiments with new node embedding computation are described in "Node Reconstruction (Inductivity)." section of our paper https://arxiv.org/pdf/2102.02302.pdf .

2. Data with weighted edges can be modelled by changing Cleora computation slightly. Per notation from our paper, you can arbitrarily manipulate the weights in the M matrix and feed greater/smaller values whenever needed to enhance/decrease edge influence (we are currently treating all edges equally). We have this feature on our desired feature list but with smaller priority than cold start initialization, so this is expected to be implemented but further down the line.

**Comment by PierceLBrooks** [comment]
@barbara3430 do you have any recommendation for how one might go about implementing this matrix influence for the simple case of an input graph structure expressed with only one complex, reflexive column?

**Comment by akshath-nykaa** [comment]
@barbara3430 thanks for Cleora, when are you planning to release a way to incorporate edge weights while computing the transition matrix?
